/**
 * Dev-time generator for lib/config-parser/aliases.ts.
 *
 * Reads the committed `tmux list-commands` output fixture
 * (lib/config-parser/fixtures/list-commands-3.6b.txt, tmux 3.6b) and emits:
 *   - COMMAND_ALIASES: alias -> canonical command name
 *   - KNOWN_COMMANDS:  every canonical command name
 *   - COMMAND_FLAG_SPECS: per command, which single-letter flags take a value
 *
 * Run with:  node scripts/gen-aliases.ts
 * (Node >= 22.6 with type stripping; the script is plain typed JS.)
 *
 * Reproducible: output depends only on the fixture file. Do not edit
 * lib/config-parser/aliases.ts by hand — edit the fixture or this script.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const fixturePath = join(
  root,
  "lib/config-parser/fixtures/list-commands-3.6b.txt",
);
const outPath = join(root, "lib/config-parser/aliases.ts");

const lines = readFileSync(fixturePath, "utf8")
  .split("\n")
  .map((l) => l.trim())
  .filter(Boolean);

const aliases: Record<string, string> = {};
const known: string[] = [];
/** command -> { flagChar -> takesValue } */
const flagSpecs: Record<string, Record<string, boolean>> = {};

for (const line of lines) {
  const m = line.match(/^([a-z0-9-]+)(?:\s+\(([a-z0-9-]+)\))?\s*(.*)$/);
  if (!m) throw new Error(`Unparseable list-commands line: ${line}`);
  const [, name, alias, rest] = m;
  known.push(name);
  if (alias) aliases[alias] = name;

  const spec: Record<string, boolean> = {};
  // Bracket groups: [-abc] boolean cluster, [-c value-name] valued flag,
  // [-L|-S|-U] alternatives (boolean).
  const groupRe = /\[([^\]]*)\]/g;
  let g: RegExpExecArray | null;
  while ((g = groupRe.exec(rest)) !== null) {
    const body = g[1];
    const valued = body.match(/^-([A-Za-z0-9])\s+\S/);
    if (valued) {
      spec[valued[1]] = true;
      continue;
    }
    const cluster = body.match(/^-([A-Za-z0-9]+)$/);
    if (cluster) {
      for (const ch of cluster[1]) spec[ch] = false;
      continue;
    }
    const alts = body.match(/^-([A-Za-z0-9])(\|-[A-Za-z0-9])+$/);
    if (alts) {
      for (const part of body.split("|")) spec[part.slice(1)] = false;
    }
    // Anything else ([command ...], [key], positional specs) is ignored.
  }
  flagSpecs[name] = spec;
}

const banner = `/**
 * GENERATED FILE — do not edit.
 *
 * Generated by scripts/gen-aliases.ts from
 * lib/config-parser/fixtures/list-commands-3.6b.txt (tmux 3.6b).
 * Regenerate with: node scripts/gen-aliases.ts
 */
`;

const aliasEntries = Object.entries(aliases)
  .map(([a, c]) => `  "${a}": "${c}",`)
  .join("\n");

const knownEntries = known.map((c) => `  "${c}",`).join("\n");

const specEntries = Object.entries(flagSpecs)
  .map(([cmd, spec]) => {
    const flags = Object.entries(spec)
      .map(([f, v]) => `"${f}": ${v}`)
      .join(", ");
    return `  "${cmd}": { ${flags} },`;
  })
  .join("\n");

const out = `${banner}
/** Alias -> canonical command name (e.g. splitw -> split-window). */
export const COMMAND_ALIASES: Record<string, string> = {
${aliasEntries}
};

/** Every canonical tmux command name (tmux 3.6b). */
export const KNOWN_COMMANDS: Set<string> = new Set([
${knownEntries}
]);

/**
 * Per command: single-letter flag -> whether the flag takes a value.
 * Derived from the [-x value] / [-abc] groups printed by list-commands.
 */
export const COMMAND_FLAG_SPECS: Record<string, Record<string, boolean>> = {
${specEntries}
};
`;

writeFileSync(outPath, out);
console.log(
  `Wrote ${outPath}: ${known.length} commands, ${Object.keys(aliases).length} aliases`,
);
